obj-y	+= imx/
obj-y	+= micam/

obj-$(CONFIG_VIDEO_ATOMISP_OV7251) += atomisp-ov7251.o
obj-$(CONFIG_VIDEO_ATOMISP_AR0330) += atomisp-ar0330.o
obj-$(CONFIG_VIDEO_ATOMISP_OV883X) += atomisp-ov883x.o
obj-$(CONFIG_VIDEO_ATOMISP_MSRLIST_HELPER) += atomisp-libmsrlisthelper.o
