# SPDX-License-Identifier: GPL-2.0
#
# Makefile for camera drivers.
#
LINUXINCLUDE		    += -I drivers/staging/media/atomisp/include/

obj-$(CONFIG_INTEL_ATOMISP) += i2c/
obj-$(CONFIG_INTEL_ATOMISP) += pci/
obj-$(CONFIG_INTEL_ATOMISP) += platform/
